CFLAGS = -g -Wall -Wno-unused-parameter
CC = gcc

PROGRAMS = main_tests

.PHONY: all clean

all: $(PROGRAMS)

main_tests: main_tests.o hachage.o testsHachage.o utils.o
	$(CC) $(CFLAGS) -o $@ $^

main_tests.o: main_tests.c
	$(CC) $(CFLAGS) -c $<

hachage.o: hachage.c
	$(CC) $(CFLAGS) -c $<

testsHachage.o: testsHachage.c  # Fix here
	$(CC) $(CFLAGS) -c $<

utils.o: utils.c
	$(CC) $(CFLAGS) -c $<

clean:
	rm -f *.o *.gch *~ $(PROGRAMS) ./rechercheMultiplesLC.txt
